// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Base.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Base.proto</summary>
  public static partial class BaseReflection {

    #region Descriptor
    /// <summary>File descriptor for Base.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpCYXNlLnByb3RvEghQcm90b2NvbCJLCghDMlNMb2dpbhIPCgdhY2NvdW50",
            "GAEgAigJEgsKA3B3ZBgCIAIoCRIUCgxzZXJ2ZXJudW1iZXIYAyACKAUSCwoD",
            "bWFjGAQgASgJIjAKCFMyQ0hlbGxvEhAKCHJhbmRzZWVkGAEgAigFEhIKCnNl",
            "cnZlcnRpbWUYAiACKAUihAEKD1MyQ0xvZ2luU3VjY2VzcxIKCgJpZBgBIAIo",
            "AxIMCgRuYW1lGAIgAigJEhQKDHNlcnZlcm51bWJlchgDIAIoBRINCgVzaGFw",
            "ZRgEIAIoBRIKCgJsdhgFIAIoBRILCgNleHAYBiACKAMSDAoEZ29sZBgHIAIo",
            "AxILCgNnZW0YCCACKAM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.C2SLogin), global::Protocol.C2SLogin.Parser, new[]{ "Account", "Pwd", "Servernumber", "Mac" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.S2CHello), global::Protocol.S2CHello.Parser, new[]{ "Randseed", "Servertime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.S2CLoginSuccess), global::Protocol.S2CLoginSuccess.Parser, new[]{ "Id", "Name", "Servernumber", "Shape", "Lv", "Exp", "Gold", "Gem" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///---------客户端到服务器---------------------------------------------------------
  ///------------c2s-------------
  ///c2s子协议号:1~登录
  /// </summary>
  public sealed partial class C2SLogin : pb::IMessage<C2SLogin>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<C2SLogin> _parser = new pb::MessageParser<C2SLogin>(() => new C2SLogin());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2SLogin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.BaseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2SLogin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2SLogin(C2SLogin other) : this() {
      _hasBits0 = other._hasBits0;
      account_ = other.account_;
      pwd_ = other.pwd_;
      servernumber_ = other.servernumber_;
      mac_ = other.mac_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2SLogin Clone() {
      return new C2SLogin(this);
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 1;
    private readonly static string AccountDefaultValue = "";

    private string account_;
    /// <summary>
    ///账号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Account {
      get { return account_ ?? AccountDefaultValue; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "account" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccount {
      get { return account_ != null; }
    }
    /// <summary>Clears the value of the "account" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccount() {
      account_ = null;
    }

    /// <summary>Field number for the "pwd" field.</summary>
    public const int PwdFieldNumber = 2;
    private readonly static string PwdDefaultValue = "";

    private string pwd_;
    /// <summary>
    ///密码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Pwd {
      get { return pwd_ ?? PwdDefaultValue; }
      set {
        pwd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "pwd" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPwd {
      get { return pwd_ != null; }
    }
    /// <summary>Clears the value of the "pwd" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPwd() {
      pwd_ = null;
    }

    /// <summary>Field number for the "servernumber" field.</summary>
    public const int ServernumberFieldNumber = 3;
    private readonly static int ServernumberDefaultValue = 0;

    private int servernumber_;
    /// <summary>
    ///服务器区号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Servernumber {
      get { if ((_hasBits0 & 1) != 0) { return servernumber_; } else { return ServernumberDefaultValue; } }
      set {
        _hasBits0 |= 1;
        servernumber_ = value;
      }
    }
    /// <summary>Gets whether the "servernumber" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasServernumber {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "servernumber" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearServernumber() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "mac" field.</summary>
    public const int MacFieldNumber = 4;
    private readonly static string MacDefaultValue = "";

    private string mac_;
    /// <summary>
    ///机器mac
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mac {
      get { return mac_ ?? MacDefaultValue; }
      set {
        mac_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "mac" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMac {
      get { return mac_ != null; }
    }
    /// <summary>Clears the value of the "mac" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMac() {
      mac_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2SLogin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2SLogin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Account != other.Account) return false;
      if (Pwd != other.Pwd) return false;
      if (Servernumber != other.Servernumber) return false;
      if (Mac != other.Mac) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAccount) hash ^= Account.GetHashCode();
      if (HasPwd) hash ^= Pwd.GetHashCode();
      if (HasServernumber) hash ^= Servernumber.GetHashCode();
      if (HasMac) hash ^= Mac.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAccount) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      if (HasPwd) {
        output.WriteRawTag(18);
        output.WriteString(Pwd);
      }
      if (HasServernumber) {
        output.WriteRawTag(24);
        output.WriteInt32(Servernumber);
      }
      if (HasMac) {
        output.WriteRawTag(34);
        output.WriteString(Mac);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAccount) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      if (HasPwd) {
        output.WriteRawTag(18);
        output.WriteString(Pwd);
      }
      if (HasServernumber) {
        output.WriteRawTag(24);
        output.WriteInt32(Servernumber);
      }
      if (HasMac) {
        output.WriteRawTag(34);
        output.WriteString(Mac);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAccount) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (HasPwd) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Pwd);
      }
      if (HasServernumber) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Servernumber);
      }
      if (HasMac) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mac);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2SLogin other) {
      if (other == null) {
        return;
      }
      if (other.HasAccount) {
        Account = other.Account;
      }
      if (other.HasPwd) {
        Pwd = other.Pwd;
      }
      if (other.HasServernumber) {
        Servernumber = other.Servernumber;
      }
      if (other.HasMac) {
        Mac = other.Mac;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            Pwd = input.ReadString();
            break;
          }
          case 24: {
            Servernumber = input.ReadInt32();
            break;
          }
          case 34: {
            Mac = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            Pwd = input.ReadString();
            break;
          }
          case 24: {
            Servernumber = input.ReadInt32();
            break;
          }
          case 34: {
            Mac = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///-----------------------------------------------
  ///---------服务器到客户端---------------------------------------------------------
  ///-------------s2c--------------------------------
  ///s2c子协议号1--发送hello包,表示连接成功,您可以登录处理
  /// </summary>
  public sealed partial class S2CHello : pb::IMessage<S2CHello>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<S2CHello> _parser = new pb::MessageParser<S2CHello>(() => new S2CHello());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<S2CHello> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.BaseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2CHello() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2CHello(S2CHello other) : this() {
      _hasBits0 = other._hasBits0;
      randseed_ = other.randseed_;
      servertime_ = other.servertime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2CHello Clone() {
      return new S2CHello(this);
    }

    /// <summary>Field number for the "randseed" field.</summary>
    public const int RandseedFieldNumber = 1;
    private readonly static int RandseedDefaultValue = 0;

    private int randseed_;
    /// <summary>
    ///客户端可以当做随机种子
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Randseed {
      get { if ((_hasBits0 & 1) != 0) { return randseed_; } else { return RandseedDefaultValue; } }
      set {
        _hasBits0 |= 1;
        randseed_ = value;
      }
    }
    /// <summary>Gets whether the "randseed" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRandseed {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "randseed" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRandseed() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "servertime" field.</summary>
    public const int ServertimeFieldNumber = 2;
    private readonly static int ServertimeDefaultValue = 0;

    private int servertime_;
    /// <summary>
    ///服务器时间      
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Servertime {
      get { if ((_hasBits0 & 2) != 0) { return servertime_; } else { return ServertimeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        servertime_ = value;
      }
    }
    /// <summary>Gets whether the "servertime" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasServertime {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "servertime" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearServertime() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as S2CHello);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(S2CHello other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Randseed != other.Randseed) return false;
      if (Servertime != other.Servertime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRandseed) hash ^= Randseed.GetHashCode();
      if (HasServertime) hash ^= Servertime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRandseed) {
        output.WriteRawTag(8);
        output.WriteInt32(Randseed);
      }
      if (HasServertime) {
        output.WriteRawTag(16);
        output.WriteInt32(Servertime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRandseed) {
        output.WriteRawTag(8);
        output.WriteInt32(Randseed);
      }
      if (HasServertime) {
        output.WriteRawTag(16);
        output.WriteInt32(Servertime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRandseed) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Randseed);
      }
      if (HasServertime) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Servertime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(S2CHello other) {
      if (other == null) {
        return;
      }
      if (other.HasRandseed) {
        Randseed = other.Randseed;
      }
      if (other.HasServertime) {
        Servertime = other.Servertime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Randseed = input.ReadInt32();
            break;
          }
          case 16: {
            Servertime = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Randseed = input.ReadInt32();
            break;
          }
          case 16: {
            Servertime = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///s2c子协议号2
  /// </summary>
  public sealed partial class S2CLoginSuccess : pb::IMessage<S2CLoginSuccess>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<S2CLoginSuccess> _parser = new pb::MessageParser<S2CLoginSuccess>(() => new S2CLoginSuccess());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<S2CLoginSuccess> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.BaseReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2CLoginSuccess() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2CLoginSuccess(S2CLoginSuccess other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      name_ = other.name_;
      servernumber_ = other.servernumber_;
      shape_ = other.shape_;
      lv_ = other.lv_;
      exp_ = other.exp_;
      gold_ = other.gold_;
      gem_ = other.gem_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2CLoginSuccess Clone() {
      return new S2CLoginSuccess(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private readonly static long IdDefaultValue = 0L;

    private long id_;
    /// <summary>
    ///玩家ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private readonly static string NameDefaultValue = "";

    private string name_;
    /// <summary>
    ///玩家名字
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "servernumber" field.</summary>
    public const int ServernumberFieldNumber = 3;
    private readonly static int ServernumberDefaultValue = 0;

    private int servernumber_;
    /// <summary>
    ///服务器区号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Servernumber {
      get { if ((_hasBits0 & 2) != 0) { return servernumber_; } else { return ServernumberDefaultValue; } }
      set {
        _hasBits0 |= 2;
        servernumber_ = value;
      }
    }
    /// <summary>Gets whether the "servernumber" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasServernumber {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "servernumber" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearServernumber() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "shape" field.</summary>
    public const int ShapeFieldNumber = 4;
    private readonly static int ShapeDefaultValue = 0;

    private int shape_;
    /// <summary>
    /// 玩家造型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Shape {
      get { if ((_hasBits0 & 4) != 0) { return shape_; } else { return ShapeDefaultValue; } }
      set {
        _hasBits0 |= 4;
        shape_ = value;
      }
    }
    /// <summary>Gets whether the "shape" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasShape {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "shape" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearShape() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "lv" field.</summary>
    public const int LvFieldNumber = 5;
    private readonly static int LvDefaultValue = 0;

    private int lv_;
    /// <summary>
    /// 玩家等级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Lv {
      get { if ((_hasBits0 & 8) != 0) { return lv_; } else { return LvDefaultValue; } }
      set {
        _hasBits0 |= 8;
        lv_ = value;
      }
    }
    /// <summary>Gets whether the "lv" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLv {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "lv" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLv() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 6;
    private readonly static long ExpDefaultValue = 0L;

    private long exp_;
    /// <summary>
    /// 玩家经验
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Exp {
      get { if ((_hasBits0 & 16) != 0) { return exp_; } else { return ExpDefaultValue; } }
      set {
        _hasBits0 |= 16;
        exp_ = value;
      }
    }
    /// <summary>Gets whether the "exp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasExp {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "exp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExp() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "gold" field.</summary>
    public const int GoldFieldNumber = 7;
    private readonly static long GoldDefaultValue = 0L;

    private long gold_;
    /// <summary>
    /// 金币
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Gold {
      get { if ((_hasBits0 & 32) != 0) { return gold_; } else { return GoldDefaultValue; } }
      set {
        _hasBits0 |= 32;
        gold_ = value;
      }
    }
    /// <summary>Gets whether the "gold" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGold {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "gold" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGold() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "gem" field.</summary>
    public const int GemFieldNumber = 8;
    private readonly static long GemDefaultValue = 0L;

    private long gem_;
    /// <summary>
    /// 钻石
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Gem {
      get { if ((_hasBits0 & 64) != 0) { return gem_; } else { return GemDefaultValue; } }
      set {
        _hasBits0 |= 64;
        gem_ = value;
      }
    }
    /// <summary>Gets whether the "gem" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGem {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "gem" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGem() {
      _hasBits0 &= ~64;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as S2CLoginSuccess);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(S2CLoginSuccess other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Servernumber != other.Servernumber) return false;
      if (Shape != other.Shape) return false;
      if (Lv != other.Lv) return false;
      if (Exp != other.Exp) return false;
      if (Gold != other.Gold) return false;
      if (Gem != other.Gem) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasServernumber) hash ^= Servernumber.GetHashCode();
      if (HasShape) hash ^= Shape.GetHashCode();
      if (HasLv) hash ^= Lv.GetHashCode();
      if (HasExp) hash ^= Exp.GetHashCode();
      if (HasGold) hash ^= Gold.GetHashCode();
      if (HasGem) hash ^= Gem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasServernumber) {
        output.WriteRawTag(24);
        output.WriteInt32(Servernumber);
      }
      if (HasShape) {
        output.WriteRawTag(32);
        output.WriteInt32(Shape);
      }
      if (HasLv) {
        output.WriteRawTag(40);
        output.WriteInt32(Lv);
      }
      if (HasExp) {
        output.WriteRawTag(48);
        output.WriteInt64(Exp);
      }
      if (HasGold) {
        output.WriteRawTag(56);
        output.WriteInt64(Gold);
      }
      if (HasGem) {
        output.WriteRawTag(64);
        output.WriteInt64(Gem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasServernumber) {
        output.WriteRawTag(24);
        output.WriteInt32(Servernumber);
      }
      if (HasShape) {
        output.WriteRawTag(32);
        output.WriteInt32(Shape);
      }
      if (HasLv) {
        output.WriteRawTag(40);
        output.WriteInt32(Lv);
      }
      if (HasExp) {
        output.WriteRawTag(48);
        output.WriteInt64(Exp);
      }
      if (HasGold) {
        output.WriteRawTag(56);
        output.WriteInt64(Gold);
      }
      if (HasGem) {
        output.WriteRawTag(64);
        output.WriteInt64(Gem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasServernumber) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Servernumber);
      }
      if (HasShape) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Shape);
      }
      if (HasLv) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Lv);
      }
      if (HasExp) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Exp);
      }
      if (HasGold) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Gold);
      }
      if (HasGem) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Gem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(S2CLoginSuccess other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasServernumber) {
        Servernumber = other.Servernumber;
      }
      if (other.HasShape) {
        Shape = other.Shape;
      }
      if (other.HasLv) {
        Lv = other.Lv;
      }
      if (other.HasExp) {
        Exp = other.Exp;
      }
      if (other.HasGold) {
        Gold = other.Gold;
      }
      if (other.HasGem) {
        Gem = other.Gem;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Servernumber = input.ReadInt32();
            break;
          }
          case 32: {
            Shape = input.ReadInt32();
            break;
          }
          case 40: {
            Lv = input.ReadInt32();
            break;
          }
          case 48: {
            Exp = input.ReadInt64();
            break;
          }
          case 56: {
            Gold = input.ReadInt64();
            break;
          }
          case 64: {
            Gem = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Servernumber = input.ReadInt32();
            break;
          }
          case 32: {
            Shape = input.ReadInt32();
            break;
          }
          case 40: {
            Lv = input.ReadInt32();
            break;
          }
          case 48: {
            Exp = input.ReadInt64();
            break;
          }
          case 56: {
            Gold = input.ReadInt64();
            break;
          }
          case 64: {
            Gem = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
